USE [BMT_Prod]
GO

/****** Object:  Table [dbo].[T_CT_ToxicityICANS]    Script Date: 6/29/2023 5:37:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_CT_ToxicityICANS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[visit] [varchar](255) NULL,
	[cupnx] [float] NULL,
	[CUPN] [int] NULL,
	[ptname] [varchar](255) NULL,
	[MRN] [int] NULL,
	[CRID] [int] NULL,
	[infdate] [datetime] NULL,
	[NTX] [nvarchar](50) NULL,
	[NTXdate] [datetime] NULL,
	[NTXther_anak] [bit] NULL,
	[NTXther_anti] [bit] NULL,
	[NTXther_cort] [bit] NULL,
	[NTXther_cortp] [bit] NULL,
	[NTXther_silt] [bit] NULL,
	[NTXther_toci] [bit] NULL,
	[NTXther_othr] [bit] NULL,
	[NTXther_othrspec] [varchar](255) NULL,
	[NTXther_none] [bit] NULL,
	[NTXassess] [varchar](255) NULL,
	[NTXassess_low] [varchar](255) NULL,
	[NTXmanif_cered] [bit] NULL,
	[NTXmanif_cva] [bit] NULL,
	[NTXmanif_cogimp] [bit] NULL,
	[NTXmanif_dcons] [bit] NULL,
	[NTXmanif_motor] [bit] NULL,
	[NTXmanif_movdis] [bit] NULL,
	[NTXmanif_perschg] [bit] NULL,
	[NTXmanif_seiz] [bit] NULL,
	[NTXmanif_spch] [bit] NULL,
	[NTXmanif_oth] [bit] NULL,
	[NTXmanif_othspec] [varchar](255) NULL,
	[NTXcered] [varchar](255) NULL,
	[NTXcered_res] [nvarchar](50) NULL,
	[NTXcered_res_dt] [datetime] NULL,
	[NTXcvadt] [datetime] NULL,
	[NTXcva_spec] [varchar](255) NULL,
	[NTXcogimp_amne] [bit] NULL,
	[NTXcogimp_cogn] [bit] NULL,
	[NTXcogimp_conc] [bit] NULL,
	[NTXcogimp_conf] [bit] NULL,
	[NTXcogimp_ence] [bit] NULL,
	[NTXcogimp_hall] [bit] NULL,
	[NTXcogimp_leuk] [bit] NULL,
	[NTXcogimp_loss] [bit] NULL,
	[NTXcogimp_ment] [bit] NULL,
	[NTXcogimp_noni] [bit] NULL,
	[NTXcogimp_psyc] [bit] NULL,
	[NTXcogimp_oth] [bit] NULL,
	[NTXcogimp_othspec] [varchar](255) NULL,
	[NTXcogimp_res] [nvarchar](50) NULL,
	[NTXcogimp_res_dt] [datetime] NULL,
	[NTXdcons] [varchar](255) NULL,
	[NTXdcons_res] [nvarchar](50) NULL,
	[NTXdcons_res_dt] [datetime] NULL,
	[NTXmotor_faci] [bit] NULL,
	[NTXmotor_guil] [bit] NULL,
	[NTXmotor_hemi] [bit] NULL,
	[NTXmotor_myel] [bit] NULL,
	[NTXmotor_para] [bit] NULL,
	[NTXmotor_oth] [bit] NULL,
	[NTXmotor_othspec] [varchar](255) NULL,
	[NTXmotor_res] [nvarchar](50) NULL,
	[NTXmotor_res_dt] [datetime] NULL,
	[NTXmovdis_acti] [bit] NULL,
	[NTXmovdis_atax] [bit] NULL,
	[NTXmovdis_cogw] [bit] NULL,
	[NTXmovdis_dysg] [bit] NULL,
	[NTXmovdis_dysk] [bit] NULL,
	[NTXmovdis_dysm] [bit] NULL,
	[NTXmovdis_gait] [bit] NULL,
	[NTXmovdis_myoc] [bit] NULL,
	[NTXmovdis_rest] [bit] NULL,
	[NTXmovdis_oth] [bit] NULL,
	[NTXmovdis_othspec] [varchar](255) NULL,
	[NTXmovdis_res] [nvarchar](50) NULL,
	[NTXmovdis_res_dt] [datetime] NULL,
	[NTXperschg_flat] [bit] NULL,
	[NTXperschg_pers] [bit] NULL,
	[NTXperschg_oth] [bit] NULL,
	[NTXperschg_othspec] [varchar](255) NULL,
	[NTXperschg_res] [bit] NULL,
	[NTXperschg_res_dt] [datetime] NULL,
	[NTXseiz] [varchar](255) NULL,
	[NTXseiz_sev] [int] NULL,
	[NTXspch] [varchar](255) NULL,
	[NTXdysph_grd] [int] NULL,
	[NTXresolve] [nvarchar](50) NULL,
	[NTXresolvedt] [datetime] NULL,
	[timestamp] [timestamp] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


